name: Main

on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: getRelease
        name: release-downloader
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "Eltirosto/Degrees-of-Lewdity-Chinese-Localization"
          latest: true
          fileName: "dol-*.zip"
      - name: Extract downloaded file
        run: |
          echo "Downloaded Chinese version DOL: ${{ steps.getRelease.outputs.tag_name }}"
          unzip -q ${{ fromJson(steps.getRelease.outputs.downloaded_files)[0] }} -d dol-release
      - name: Construct PWA
        run: |
          cp -r .github/pwa/* dol-release/
          mv "dol-release/Degrees of Lewdity.html" dol-release/index.html
      - name: Modify HTML
        shell: python3 {0}
        run: |
          with open("dol-release/index.html", "r+", encoding="utf-8") as index_html_file:
            index_html = index_html_file.read()
            insert_index = index_html.find("<head>") + 7
            index_html = index_html[:insert_index] + \
                "<link rel=\"manifest\" href=\"manifest.json\">\n" + index_html[insert_index:]
            insert_index = index_html.find("<body>") + 7
            index_html = index_html[:insert_index] + \
                "    <script>\n" + \
                "        if (typeof navigator.serviceWorker !== 'undefined') {\n" + \
                "            navigator.serviceWorker.register('sw.js')\n" + \
                "        }\n" + \
                "    </script>\n" + index_html[insert_index:]
            index_html_file.seek(0)
            index_html_file.truncate()
            index_html_file.write(index_html)
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          github-comment: false
          vercel-args: --prod
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_TEAM_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: dol-release
      - name: Modify manifest.json
        shell: python3 {0}
        run: |
          import json
          with open("dol-release/manifest.json", "r+", encoding="utf-8") as manifest_file:
            manifest_json = json.loads(manifest_file.read())
            manifest_json["scope"] = "/dol-pwa/"
            manifest_json["start_url"] = "/dol-pwa/"
            manifest_json["shortcuts"][0]["url"] = "/dol-pwa/"
            manifest_file.seek(0)
            manifest_file.truncate()
            manifest_file.write(json.dumps(manifest_json, indent=2))
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_dir: dol-release
          keep_history: false
          target_branch: gh-pages
      
            
